### PR TITLE
Add ignore last-else hint

### LINKED ISSUE #781: 'istanbul ignore else' inbetween a 'else' and 'if' is ignored
See also #230.

screen shot 2017-03-16 at 4 26 29 pm

You can work around it with some extra braces:

screen shot 2017-03-16 at 4 28 13 pm

### PR DESCRIPTION
**Pull request by fgerschau**
Closes #781 

This is my first contribution here. I'm not sure using this.currentState for this is the best way to do it but I'm open to suggestions :)

### CODE REVIEW

**Comment by zakjan** [comment]
Such feature would be really helpful. As #781 shows, there is currently missing a  straightforward way to ignore the last else block of a if/elseif/else. In my case, I usually list all possible states explicitly for readability, and use else block for invalid state. Even though in theory it's impossible to reach such else block by code, it could reached be by a bug elsewhere in code or invalid user input.

```
// type can be X or Y only
if (type instanceof X) {
    // do something
} else if (type instanceof Y) {
    // do something else
} else {
    throw new Error("Invalid state");
}
```

**Comment by fgerschau** [comment]
wrong repository (this one is not being maintained)

**Comment by zakjan** [comment]
@fgerschau Could you please port the PR to the correct repository? Thanks a lot!

**Comment by fgerschau** [comment]
@zakjan it's basically an entire different codebase. Check out [v2](https://github.com/istanbuljs/istanbuljs). Unfortunately I doubt I will have time to do that any time soon

**Pull request closed without merging**
