### PR TITLE
Adding ability to set custom block name in teamcity report

### PR DESCRIPTION
**Pull request by aryelu**

### CODE REVIEW

**Comment by gotwarlost** [comment]
Could you add this key to the `getDefaultConfig()` method with its default value so that people can discover - via `istanbul help config` - that this option exists?

LGTM otherwise. Thanks.

**Comment by gotwarlost** [comment]
Also, if you are familiar with the teamcity internals, could you help review https://github.com/gotwarlost/istanbul/pull/264 ? Thanks in advance.

**Comment by aryelu** [comment]
I've updated the commit with your comments, I'll check about #264

**Comment by gotwarlost** [comment]
available in v0.3.20. Thanks!

**Pull request merged**
