### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fhemberger**
handlebars@3.0.0 uses the vulnerable version uglify-js@2.3.6
https://nodesecurity.io/advisories/module/uglify-js

### CODE REVIEW

**Comment by fhemberger** [comment]
@gotwarlost Okay, one test seem to fail on nodejs@4.0.0: "should produce identical instrumentation results when instrumentation run on browser v/s nodejs" – should I remove the travis setting again or do you want to look into this?

**Comment by gotwarlost** [comment]
Let's remove the new travis setting for now and get this merged. I need to figure out what is going on here. Thanks!

**Comment by fhemberger** [comment]
Okay, removed node@4 testing, now travis is green again.

**Comment by shinnn** [comment]
Fixed in https://github.com/gotwarlost/istanbul/commit/48dc2de37c2b5cc318ee600e8adad8bccde8cd1a.

**Pull request closed without merging**
