### PR TITLE
Update handlebars dependency

### PR DESCRIPTION
**Pull request by mobilutz**
There is an NPM Security Advisory for handlebars:
https://www.npmjs.com/advisories/755

### CODE REVIEW

**Comment by SteveSonoa** [comment]
Hoping this change is accepted.

**Comment by mobilutz** [comment]
@SteveSonoa I don't think that this Deprecated repo will see any change anymore. 🙁 

But lets hope.

**Comment by hicom150** [comment]
Maybe an exceptional release could be made as many libraries still rely on this dependency.
Lets hope.

**Comment by mobilutz** [comment]
I do not need this fix anymore. Closing this as it is also 3 years old!

**Pull request closed without merging**
