### PR TITLE
Add support for instrumenting code with es modules

### PR DESCRIPTION
**Pull request by adamjmcgrath**
- Add support for instrumenting code that contains es import and export statements.
- Also transpiling es6 in tests so they can be run on node versions that don't support those features

### CODE REVIEW

**Comment by adamjmcgrath** [comment]
It's failing on the Node.js 0.10 build, will take a look

**Comment by adamjmcgrath** [comment]
If transpiling the unsupported es6 tests is too controversial I can remove it, but it would be useful to be able to pass: `sourceType: 'module'` to escodegen - it would for example enable Ember apps to report coverage on their es6 code (Ember apps use es import/export) - I'm relying on this change to create an ember-istanbul addon

**Comment by gotwarlost** [comment]
Sorry for the delay. I haven't been paying too much attention to open-source work recently.

The code changes look ok.

Please remove all the transpilation in the tests and re-instate the esprima check. I'm not inclined to take all these additional dependencies. The instrumenter is going thru a surgery and I don't want to add all of this extra stuff in the middle of that exercise. Thanks.

**Comment by adamjmcgrath** [comment]
No problem - have removed the transpilation in the tests and restored the esprima checks

**Comment by gotwarlost** [comment]
LGTM. Could you squash the commits?

**Comment by adamjmcgrath** [comment]
squashed

**Pull request merged**
