### PR TITLE
Update cobertura reporter to support ignores. 

### PR DESCRIPTION
**Pull request by BonsaiDen**
Since the Cobertura Report XML cannot handle ignores directly, this will mark the ignored functions, statements and branches as covered.

### CODE REVIEW

**Comment by eiriksm** [comment]
+1 on this one. Tested and works for me.

Let me know if I can help in any way

**Comment by lo1tuma** [comment]
Seems like the build on travis failed only for node 0.8 during `npm install`.
@gotwarlost can you re-run the travis build?

**Comment by snajo** [comment]
+1

**Comment by gnuheidix** [comment]
+1

**Comment by BonsaiDen** [comment]
Any updates on this? Would really like to rid of the custom git repo in `package.json` :)

PS: I just pulled in all the changes from master into my branch. Everything seems to be working fine.

**Comment by sh1mmer** [comment]
+1 on this. cc @gotwarlost

**Comment by gotwarlost** [comment]
@BonsaiDen - could you reconcile this work with https://github.com/gotwarlost/istanbul/pull/238 ? Looks like that one is also trying to accomplish what you are doing here but in a more general way that is not cobertura-specific.

**Comment by BonsaiDen** [comment]
@gotwarlost Sure thing! I'll check tomorrow on whether this has the same results as the changes I made for cobertura.

**Comment by gotwarlost** [comment]
I think this is fixed via #238 ? Closing. Lemme know if this is not the case.

**Pull request closed without merging**
