### PR TITLE
'flow' report/web app for interactively fixing coverage

### PR DESCRIPTION
**Pull request by aparajita**
My typical workflow with istanbul is:

* Run `istanbul cover --report html`
* Open `coverage/index.html`
* Go through each file
* Add a test to cover each uncovered function/statement/branch, or add an `istanbul ignore` directive.
* Repeat until there are no uncovered lines.

In the context of this workflow, I found the html report has a few weaknesses:

* **Information overload** – The only thing I'm interested in is how many uncovered items remain. The summary pages are crammed full of numbers that don't matter. It's very hard to pick out what's relevant.

*  **Discoverability** – Within a file view, there are no navigation aids to help find uncovered items. I find myself scrolling through, hoping I'll catch a colored line. Then I hope I won't lose my place later on.

* **Tracking fixes** – The html report is static, so there is no way for me to keep track of which items I have fixed before I run istanbul again. This quickly becomes tiresome.

In an effort to address all of these weaknesses, I created a new report format called "flow" (for "workflow"), which is actually a full-blown web app. IMHO, it's the killer app for istanbul.

Detailed documentation is included. Please give it a try!

### CODE REVIEW

**Comment by aparajita** [comment]
Looks like I need to fix some stylistic errors.

**Comment by aparajita** [comment]
Looks like it's failing with earlier versions of node, I'll fix that.

**Comment by aparajita** [comment]
@gotwarlost Any chance you can look at this? Would you consider adding me as a contributor to the project? I rely heavily on istanbul and I'd be happy to help out.

**Comment by gotwarlost** [comment]
Oops, sorry for not replying. Been busy with working on istanbul 1.0. In which I plan to allow outside-of-core reports using `--report foo` as long as you write the report in a module called
`istanbul-foo-report`. I need to check on the status of this extension mechanism but it can be trivially added.

Thing is, I already have a hard time maintaining current reports and do not want to increase the core footprint. Which I why I prefer new reports to be written using the extension mechanism.

However, the reporting interface has changed for 1.0 and the new reports can be found here:

https://github.com/istanbuljs/istanbul-reports

See also: https://github.com/istanbuljs/istanbul-lib-report for context on the visitor mechanism.

Yeah, I still need to publish the docs. For now, the library has decent JSdoc

**Comment by aparajita** [comment]
I'll look into using the extension mechanism in 1.0, thanks.

**Pull request closed without merging**
