### PR TITLE
update to esprima 3

### PR DESCRIPTION
**Pull request by patrickkettner**
trying to use istanbul to instrument some basic es6 code, and it can't currently because of the lack of esprima supporting it. This fixes that, with three very tiny modifications.
1. update the esprima dep in package.json
2. update the path to esprima in the server test (the package changed up its file structure)
3. escape a single forward slash in prettify.js. Without this, the browser and server generate two different versions of the file (the only difference being the change I made here).

11 whole bits, beings a whole mess of new features.

### CODE REVIEW

**Comment by DavidGDD** [comment]
Updated needed for [Issue #613](https://github.com/gotwarlost/istanbul/issues/613)

**Comment by jorgemsrs** [comment]
Any news on this?

**Comment by mayank-patel** [comment]
Can we have this merge in please ?

**Comment by scottinet** [comment]
This is REALLY needed, I currently cannot use istanbul on code using some new ES6 keywords because of esprima 2 :-(

**Comment by jadengore** [comment]
Bump on this, I'm trying to use ES7 syntax (exponentiation operator `**`) and esprima is throwing errors.

This branch fixes it and I would really appreciate the merge.

**Comment by blatiusfp** [comment]
Would really appreciate this getting merged.

**Comment by scottinet** [comment]
Got the same problem a few months ago and the deprecation notice wasn't there at the time. Just for the heads up: this version of istanbul is deprecated in favor of [nyc](https://github.com/istanbuljs/nyc), which supports ES6 syntax.

**Comment by blatiusfp** [comment]
Ok, thank you.

**Pull request closed without merging**
