### PR TITLE
added missing systemmessages for teamcity reporter

### PR DESCRIPTION
**Pull request by hulvei3**
TeamCity supports the 'block' coverage report variable, but it only shows it if both **percentage**, **total** and **covered** counts are written out as system messages. The documentation is missing out these vars, but by guessing the naming I managed to get the block coverage report-chart shown.
https://confluence.jetbrains.com/display/TCD8/Custom+Chart#CustomChart-DefaultStatisticsValuesProvidedbyTeamCity

I have defined branches as what teamcity defines as _blocks_, as this makes more sense to me than statements.

### CODE REVIEW

**Comment by gotwarlost** [comment]
I don't mind merging this PR but I don't know enough of teamcity to review the code. cc @chrisgladd - original author of teamcity support - for his opinion.

**Comment by hulvei3** [comment]
@chrisgladd fancy a review?

**Comment by aryelu** [comment]
_Branches_ != _Blocks_, for the next example:
```js
var x = true ? 3 : 5;
```
_Branch coverage_ == 50% while _Block coverage_ == 100%

**Comment by gotwarlost** [comment]
@aryelu @hulvei3 - what needs to be done with this PR? I'm trying to merge/ close all PRs that involve reports since I have a biggish refactor in mind...

**Comment by aryelu** [comment]
@gotwarlost close it. I think it's better to add a custom chart for this

**Pull request closed without merging**
