### PR TITLE
Document colors legend

### PR DESCRIPTION
**Pull request by rougeth**
Just add to readme file what was discussed on #111

### CODE REVIEW

**Comment by rchapman-eb** [comment]
Was this never merged? This resource on SO seems like the only place to get a clear explanation of the instanbul report: https://stackoverflow.com/questions/26618243/how-do-i-read-an-istanbul-coverage-report.

**Comment by rosschapman** [comment]
Was this never merged? This resource on SO seems like the only place to get a clear explanation of the instanbul report: https://stackoverflow.com/questions/26618243/how-do-i-read-an-istanbul-coverage-report.

**Comment by rougeth** [comment]
¯\_(ツ)_/¯

**Comment by rougeth** [comment]
The project was deprecated.

**Pull request closed without merging**
