### PR TITLE
Add test support for Node 4 and 5

### PR DESCRIPTION
**Pull request by kpdecker**
This required a very minor modification to the prettify library due to differences in how RegExp.toString works with / under modern node instances.

```
diff phanton.test.js node4.test.js
1668c1668
<   [PR.PR_DECLARATION, /^{{[#^>/]?\s*[\w.][^}]*}}/],
---
>   [PR.PR_DECLARATION, /^{{[#^>\/]?\s*[\w.][^}]*}}/],
```

The original regex contained `[#^>/]` and under the newer V8 versions, the toString version rendered as `[#^>\/]`. By altering the source to have the escape character, the test works across all major versions of Node.

### CODE REVIEW

**Comment by kpdecker** [comment]
I expect travis to fail as this does not have 1a6802f as I wanted to avoid merge dependencies there. Can cherry pick as necessary if #480 isn't desired for whatever reason.

**Comment by gotwarlost** [comment]
Yikes, I cannot change vendor code in my source tree. That would be bad behavior and might be some sort of a license violation.

I'm closing this PR since a 1.0 version will be delivered shortly into which I'll add the Node 4.x targets.

**Comment by kpdecker** [comment]
What do you mean "change vendor code"? This is just updating the test config to run tests against modern node version.

**Comment by kpdecker** [comment]
Sorry, this sat around for so long that I forget about the vendor change and didn't see the diff since it was compressed. Fair enough, I wasn't completely comfortable with that either.

When will 1.0 come out? The project feels like it's stagnated at little bit given the delay on PR response, etc.

**Comment by gotwarlost** [comment]
@kpdecker - I agree. Although the latest round of stagnation is not due to my lack of attention to this project but a focus on a v1 version to clean up the APIs etc. istanbul has gathered a lot of cruft from a lot of changes and an unwillingness on  my part to break backwards compatibility. At some point, I just gave up trying to add source maps to this code base and worked on a refactored version instead.

I have already started committing a bunch of stuff under this org (https://github.com/istanbuljs) and will be making a few more backwards incompatible changes before declaring v1 ready. Right now all versions are 1.0.0.alpha.x and I will make a proper 1.0 after giving people a chance to test this stuff and making sure it all works.

I need a couple more days with the source map thing to declare this version testable (also need to document all backwards incompatibilities so that people don't go crazy figuring out what changed). I would love to get your help (and from others as well) in moving this forward.

**Comment by kpdecker** [comment]
Great to hear! Istanbul is vital for my development process and I've been running my own fork for quite awhile now to handle source maps primarily would be good to get back on an official branch there.

Glad to help out however you need in testing and I'll do my best to follow along on that org.

**Pull request closed without merging**
