### PR TITLE
HTML report remapping according to source maps

### PR DESCRIPTION
**Pull request by kinday**
This PR integrates [`remap-istanbul`](https://www.npmjs.com/package/remap-istanbul) mentioned in #212 and adds `--remap` option.

### CODE REVIEW

**Comment by tilgovi** [comment]
How does this compare to the source-map branch? Is it the same idea, but with the code extracted into another module?

**Comment by kinday** [comment]
@tilgovi, I missed this branch somehow. Tried it out and got coverage report with transpiled code highlighted as if it was ES6 code.

image

**Comment by blakeembrey** [comment]
If something like this were to exist, can it not read from the in-memory file store? Otherwise it won't work with in-memory transpilers.

**Comment by kinday** [comment]
Seems like it’s not relevant anymore.

**Pull request closed without merging**
