### PR TITLE
swap fileset for glob, Fixes #638

### LINKED ISSUE #638: Deprecate fileset
Hi!

I'm opening this issue to start a thread on the possibility to deprecate https://github.com/mklabs/node-fileset

I recently merged a pending PR from @isaacs (mklabs/node-fileset#22), which

> may or may not be a breaking change from fileset's pov. ([changelog](https://github.com/mklabs/node-fileset/blob/master/CHANGELOG.md#100-2016-06-01))

to quote Isaacs. So I bumped filset to a major 1.0 version which should save you from any trouble.

---

I really really appreciate that you choose to rely on it and build istanbul on top of it. But, to be honest, fileset is a package I wrote a long time ago and never really used it. I always either used just glob with the ignore pattern or redone the filtering on top of globs results before glob 5.

I'm considering deprecating the package in favour of newer, better similar packages like @sindresorhus https://github.com/sindresorhus/globby, or simply glob itself with the `options.ignore` patterns.

This should help with performance (as the minimatch ignore is done internally by glob, avoiding one costly glob call on all ignore patterns) and issues like #556 

I can maybe help in the migration process by opening a PR to switch from fileset to globby, or just glob's with `options.ignore`.

Let me know :)

Thanks for building Istanbul.

### PR DESCRIPTION
**Pull request by popomore**
I fixed the testcase picking from #648 and delete glob from devDependencies.

It can be closed once #648 have been merged.

### CODE REVIEW

**Comment by popomore** [comment]
#638

**Comment by popomore** [comment]
@mklabs @gotwarlost any suggestion?

**Comment by popomore** [comment]
ping @mklabs @gotwarlost

**Comment by mklabs** [comment]
Hi @popomore I really don't know what to do or to say. I personally think this is a good move and a really good PR. :+1:

**Comment by popomore** [comment]
now istanbul will break synk causing minimatch

**Comment by popomore** [comment]
ping @gotwarlost

**Comment by popomore** [comment]
@gotwarlost do you recommend to use nyc instead of istanbul?

**Comment by popomore** [comment]
ping @gotwarlost

**Comment by maxkoryukov** [comment]
@gotwarlost, it is really useful PR, could you merge it? This PR solves all problems with `fileset` and there are no failures (mentioned [here](https://github.com/gotwarlost/istanbul/issues/653#issuecomment-234158306))

Also:
* close PR #648 (PR with similar purpose)
* close PR #658 (PR with similar purpose)
* fix #638 
* fix #678
* fix #653

**Comment by maxkoryukov** [comment]
I have tried to attach all related issues and pull requests

**Comment by maxkoryukov** [comment]
@gotwarlost, it is really useful PR, could you merge it? This PR solves all problems with `fileset` and there are no failures (mentioned [here](https://github.com/gotwarlost/istanbul/issues/653#issuecomment-234158306))

Also:
* closes #648 (**ORIGINAL** PR with similar purpose)
* closes #658 (PR with similar purpose)
* fix #638 
* fix #678
* fix #653

@popomore , if you will mention this list of issues in one of your commits' messages, then them all will become closed on merging

**Comment by popomore** [comment]
Thx @maxkoryukov, I have pushed with message body.

**Comment by popomore** [comment]
ping @gotwarlost

**Comment by maxkoryukov** [comment]
waiting for @gotwarlost

**Comment by gotwarlost** [comment]
Thanks for the PR. Sorry for the delay in merging this. Have been busy with other things...

**Comment by gotwarlost** [comment]
available in `v0.4.5`

**Comment by maxkoryukov** [comment]
Wooohooo)) You did it! Thanks!

**Comment by maxkoryukov** [comment]
@popomore , @graingert thank you, for the fix;)

**Pull request merged**
