### PR TITLE
update ignore code example for UMD

### PR DESCRIPTION
**Pull request by pegurnee**
Just a small addition to the ignoring-code md regarding a popular way to use UMD wrappers.

### CODE REVIEW

**Comment by gotwarlost** [comment]
Hi @pegurnee - the documentation seems confusing now. It's the same code snippet in both places with different docs? Either my original example was wrong and we should just fix the placement of the ignore there or your new code snippet needs to be different in some way?

**Comment by pegurnee** [comment]
I definitely didn't intend to make it more confusing!

Looking at this again, I think I just misunderstood what was going on. The UMD wrapper you have displayed is not in the same format as [umdjs](https://github.com/umdjs/umd); putting the ignore comment at the top of the UMDjs standard would cause the entire program to be ignored, wrapper and all. 

Moving the ignore to the `if` statement in the wrapper solves that issue on both of the formats.

**Comment by pegurnee** [comment]
They aren't exactly the same code snippets:
the last line in yours:
```javascript
})(this, fn);
```
the last line in the [umdjs](https://github.com/umdjs/umd) version (effectively):
```javascript
}(this, fn));
```

**Comment by pegurnee** [comment]
@gotwarlost is the most recent version less confusing? Just moving the ignore next above the `if` appears to work in both of the models

**Pull request merged**
