### PR TITLE
Add support for es6 super

### PR DESCRIPTION
**Pull request by sterlinghw**
See #414 and estools/escodegen#252

### CODE REVIEW

**Comment by sterlinghw** [comment]
The first build failed because the latest escodegen (1.7) did not provide a prebuilt minified browser version on github like previous versions. This is why I removed this dependency and allowed the tests to build it manually.

**Comment by ronkorving** [comment]
:+1: please

**Comment by gotwarlost** [comment]
:+1: - sorry for the delay in review

**Comment by ronkorving** [comment]
@gotwarlost thank you so much! looking forward to a release :)

**Comment by thebearingedge** [comment]
Hi guys, thanks for the excellent tool. I just started using ES6 classes and ran into missing super support. On `0.3.19` I'm getting
```bash
{ range: [ 284, 289 ],
  loc:
   SourceLocation {
     start: Position { line: 12, column: 4 },
     end: { line: 12, column: 9 } },
  type: 'Super' }
Unsupported node type:Super
Transformation error; return original code
[TypeError: this[type] is not a function]
```
Did the latest merge add support for `super` or am I misreading?

**Comment by thebearingedge** [comment]
Oh, scratch that, I see it's still in the works. Thanks!

**Comment by ronkorving** [comment]
It's just been merged half an hour ago :)

**Comment by thebearingedge** [comment]
Gotcha. Saw the old commit message on `package.json` and thought. _Now what did I do wrong?!_ :)

**Comment by gotwarlost** [comment]
available in v0.3.20. Thanks!

**Comment by thebearingedge** [comment]
:trophy: Fantastic!

**Comment by sterlinghw** [comment]
v0.3.21 reverts this change

**Comment by ronkorving** [comment]
Please re-release.

**Comment by davglass** [comment]
Fixed in #455

**Pull request merged**
